/* ============================================================
   FEIFH Link — data dasar (seed data)
   Ini adalah data BAWAAN yang dipakai saat panel admin belum
   pernah dipakai untuk mengubah apa pun di browser ini.

   Begitu Admin menambah/mengubah/menghapus data lewat admin.html,
   perubahan disimpan di localStorage browser tersebut dan akan
   dipakai menggantikan data di file ini (lihat script.js & admin.js).

   Untuk membuat perubahan permanen di semua perangkat, gunakan
   tombol "Unduh data.js" di panel admin lalu unggah file hasil
   unduhan itu untuk menimpa file data.js ini, kemudian deploy ulang.
   ============================================================ */

const CATEGORIES = [
  { id: "makanan", label: "Makanan", icon: "🍜" },
  { id: "minuman", label: "Minuman", icon: "🥤" },
  { id: "warung", label: "Warung", icon: "🏪" },
  { id: "jasa", label: "Jasa", icon: "🔧" },
];

// Data banner website — bisa diubah lewat panel admin > Pengaturan Banner
const BANNER = {
  gambar: "", // URL gambar banner (kosong = pakai SVG default)
  aktif: false, // true = tampilkan gambar, false = tampilkan SVG
};

// Data teks website — bisa diubah lewat panel admin > Pengaturan Teks
// Setiap key adalah ID elemen HTML yang akan diisi teks ini.
const SITE_TEXT = {
  heroEyebrow: "Katalog Digital UMKM · Kampung Suaran",
  heroTitle: "Jalan-jalan kampung, temukan usahanya.",
  heroDesc: "FEIFH Link mengumpulkan seluruh UMKM Kampung Suaran dalam satu tempat — lengkap dengan lokasi, jam buka, dan kontak WhatsApp, supaya Anda tinggal datang atau menghubungi langsung.",
  searchPlaceholder: "Cari nama usaha, kategori, atau lokasi…",
  stat1: "UMKM terdaftar",
  stat2: "Kategori usaha",
  stat3: "Kampung, satu tautan",
  kategoriHeading: "Mau cari yang mana hari ini?",
  katalogHeading: "Usaha di Kampung Suaran",
  aboutEyebrow: "Tentang FEIFH Link",
  aboutTitle: "Bukan marketplace. Ini jalan pintas ke tetangga Anda sendiri.",
  aboutDesc: "FEIFH Link tidak menjual apa pun dan tidak memproses pesanan. Website ini murni katalog: kami menautkan Anda ke lokasi dan nomor WhatsApp pelaku UMKM, lalu transaksi terjadi langsung antara Anda dan mereka — sama seperti membeli di warung sebelah rumah, hanya lebih mudah ditemukan.",
  aboutPoint1Title: "Terpusat",
  aboutPoint1Desc: "Seluruh UMKM kampung, dari makanan sampai jasa, ada dalam satu tautan.",
  aboutPoint2Title: "Langsung terhubung",
  aboutPoint2Desc: "Klik WhatsApp atau Google Maps, langsung terhubung ke pelaku usaha.",
  aboutPoint3Title: "Selalu diperbarui",
  aboutPoint3Desc: "Data dikelola admin kampung, sehingga informasi tetap akurat.",
  adminNote: "Punya usaha di Kampung Suaran dan belum terdaftar? Hubungi admin website untuk didaftarkan ke dalam katalog.",
  footerText: "Katalog Digital UMKM Kampung Suaran · MVP 1.0",
};

const UMKM_DATA = [
  {
    id: 1,
    nama: "Trenggalek Jaya HO",
    kategori: "warung",
    icon: "🍛",
    deskripsi: "toko ini menjual berbagai kebutuhan sehari-hari seperti sembako dan peralatan rumah tangga dengan harga yang terjangkau.",
    alamat: "JL.raja diwa tinnyu, RT02,kampung suaran ( Samping  GG.Harapan)",
    jam: "05.00– 22.00 WITA",
    whatsapp: "",
    mapsQuery: "toko trenggalek jaya kampung suaran",
    fotoUsaha: "https://ibb.co.com/zTb9m8hz",
    fotoProduk: "",
    latitude: "2,0143812",
    longitude: "117,6510919",
    buka: true,
  },
  {
    id: 2,
    nama: "toko sembako rizky adelia",
    kategori: "kategori-1785738108705",
    icon: "🍢",
    deskripsi: "Toko ini menjual berbagai kebutuhan sehari-hari, seperti sembako dan peralatan rumah tangga. dengan harga yang terjangkau.",
    alamat: "Jl. raja diwa tinnyu, RT02,kampung suaran ( depan toko trenggalek Jaya HO)",
    jam: "05.00-22.00 WITA",
    whatsapp: "",
    mapsQuery: "Toko sembako rizky adelia kampung suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 3,
    nama: "Warung pinarak",
    kategori: "makanan",
    icon: "🥟",
    deskripsi: "menyajikan aneka masakan khas rumahan dengan rasa otentik dan harga yang pas di kantong",
    alamat: "Jl. raja diwa tinnyu, RT02,kampung suaran",
    jam: "09.00-21.30 WITA",
    whatsapp: "6282150119167",
    mapsQuery: "Warung pinarak",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014327",
    longitude: "117.650903",
    buka: true,
  },
  {
    id: 4,
    nama: "Masha Cell",
    kategori: "jasa",
    icon: "🥥",
    deskripsi: "Kami melayani isi pulsa & paket data, transfer/tarik tunai, top up, pembayaran tagihan (listrik, air, wifi), hingga jasa fotocopy, print, dan desain (undangan & spanduk). Cepat, mudah, dan terpercaya!",
    alamat: "Jl. raja diwa tinnyu/ jalan poros RT02,kampung suaran",
    jam: "08.00-22.00WITA",
    whatsapp: "6281258245764",
    mapsQuery: "Masha cell kampung suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 5,
    nama: "penjahit suaran sejahtera",
    kategori: "jasa",
    icon: "☕",
    deskripsi: "Menerima jahit baru dan permak (potong celana, ganti resleting, kecilkan baju). Hasil rapi, pengerjaan cepat, dan harga bersahabat untuk warga sekitar!",
    alamat: "Jl.raja diwa tinnyu, RT02,kampung suaran",
    jam: "07.00 – 22.00WITA",
    whatsapp: "6285248527118",
    mapsQuery: "Penjahit mama yusuf",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014548",
    longitude: "117.649873",
    buka: true,
  },
  {
    id: 6,
    nama: "Warung mama Riyan",
    kategori: "makanan",
    icon: "🧺",
    deskripsi: "Solusi santap siang dan malam Anda. Menyajikan beragam menu favorit harian yang dimasak segar setiap hari dengan pelayanan cepat dan tempat yang nyaman.",
    alamat: "gang masuk PT TANJUNG REDEB HUTANI",
    jam: "07.00-00.00WITA",
    whatsapp: "6285369393553",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 7,
    nama: "warung mama AL",
    kategori: "makanan",
    icon: "🏪",
    deskripsi: "Solusi santap siang dan malam Anda. Menyajikan beragam menu favorit harian yang dimasak segar setiap hari dengan pelayanan cepat dan tempat yang nyaman.",
    alamat: "Jl. raja diwa tinnyu, RT03,kampung suaran",
    jam: "09.00-00.00 WITA",
    whatsapp: "6282148690965",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 8,
    nama: "Ridhoqua",
    kategori: "minuman",
    icon: "🥥",
    deskripsi: "Penyedia kebutuhan harian masyarakat yang melayani pengisian ulang air galon bersih, penjualan bensin eceran, serta tabung gas LPG.",
    alamat: "Jl.raja diwa tinnyu, RT03,kampung suaran",
    jam: "07.00-22.00",
    whatsapp: "6285171614376",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 9,
    nama: "ES TEH untuk negeri",
    kategori: "minuman",
    icon: "🧵",
    deskripsi: "Segarkan harimu di Es Teh Negeri! Menghadirkan kenikmatan es teh racikan asli anak negeri dengan berbagai topping dan varian rasa seru—mulai dari Original, Lemon, Milk Tea, hingga varian rasa buah yang siap melepaskan dahaga kapan saja.",
    alamat: "Jl. raja diwa tinnyu, RT02,kampung suaran ( depan gedung serba guna suaran)",
    jam: "09.00-22.00WITA",
    whatsapp: "6281347280752",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 10,
    nama: "Warung sayur arema",
    kategori: "warung",
    icon: "🧼",
    deskripsi: "warung ini menyediakan aneka sayuran segar, bumbu dapur, dan kebutuhan masak sehari hari dengan harga terjangkau.",
    alamat: "Jl. raja diwa tinnyu, RT02,kampung suaran ( Samping es teh untuk negeri)",
    jam: "06.00-18.00WITA",
    whatsapp: "6281352480751",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 1785736095369,
    nama: "Toko ana",
    kategori: "kategori-1785738108705",
    icon: "🏬",
    deskripsi: "Toko ini menyediakan koleksi fashion yang nyaman di pakai dan cocok untuk berbagai gaya, toko ini juga menyediakan berbagai aksesoris dan skincare.",
    alamat: "Jl. raja diwa tinnyu, RT02,kampung suaran",
    jam: "08.00-22.00WITA",
    whatsapp: "6282290737476",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 1785736788565,
    nama: "Warung bakso dan mie ayam mak QYLA",
    kategori: "makanan",
    icon: "🏬",
    deskripsi: "Warung ini menyediakan aneka menu lezat dengan cita rasa khas dan harga yaang terjangkau.",
    alamat: "Jl.raja diwa tinnyu, RT04,kampung suaran ( dekat pukesmas)",
    jam: "11.00-23.00WITA",
    whatsapp: "6285693660450",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 1785736940814,
    nama: "warung biru arema",
    kategori: "makanan",
    icon: "🏬",
    deskripsi: "warung ini menyediakan aneka hidangan rumahan dengan pelayanan ramah, dan harga yang terjangkau.",
    alamat: "Jl.raja diwa tinnyu, RT04,kampung suaran",
    jam: "10.00-22.00WITA",
    whatsapp: "6287776659000",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 1785737461495,
    nama: "Toko sinar bone",
    kategori: "kategori-1785738108705",
    icon: "🏬",
    deskripsi: "Toko ini menyediakan berbagai kebutuhan pokok dan keperluan rumah tangga sehari hari.",
    alamat: "Jl.raja diwa tinnyu, RT04,suaran kadasa",
    jam: "06.00-23.00WITA",
    whatsapp: "6285880173693",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 1785738604090,
    nama: "Batuah raya",
    kategori: "kategori-1785738108705",
    icon: "🏬",
    deskripsi: "Toko ini menyediakan berbagai bahan, peralatan, dan perlengkapan dasar untuk kebutuhan konstruksi, renovasi, serta perbaikan rumah atau gedung.",
    alamat: "Jl.raja diwa tinnyu, RT02,suaran kadasa",
    jam: "08.00-19.00WITA",
    whatsapp: "6285346545352",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 1785738793700,
    nama: "Ngopi nah!",
    kategori: "minuman",
    icon: "🏬",
    deskripsi: "Cafe ini menyajikan berbagai olahan minuman kopi, hidangan pendamping yang nyaman untuk bersantai.",
    alamat: "Jl.raja diwa tinnyu, RT02,suaran kadasa",
    jam: "10.00-23.00WITA",
    whatsapp: "6285155155374",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 1785739065367,
    nama: "Lapak al fatir",
    kategori: "warung",
    icon: "🏬",
    deskripsi: "warung ini menyediakan berbagai jenis ikan, dan ayam.",
    alamat: "Jl.raja diwa tinnyu, RT02,suaran kadasa",
    jam: "07.00-21.00WITA",
    whatsapp: "6285175217992",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 1785739359894,
    nama: "AZ AZAHRA SHOP",
    kategori: "kategori-1785738108705",
    icon: "🏬",
    deskripsi: "Toko ini menyediakan berbagai koleksi fashion,dan aksesoris pendukung.",
    alamat: "Jl.raja diwa tinnyu, RT02,suaran simpanng",
    jam: "06.00-21.00WITA",
    whatsapp: "",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 1785739570087,
    nama: "Adi karya jaya motor",
    kategori: "jasa",
    icon: "🏬",
    deskripsi: "Bengkel ini menyediakan berbagai jasa untuk kendaraan bermotor, mesin atau peralatan teknis lainnya.",
    alamat: "Jl.raja diwa tinnyu, RT02,suaran simpang",
    jam: "07.00-17.00WITA",
    whatsapp: "6282148783556",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
  {
    id: 1785739888825,
    nama: "Pencucian motor sanggam",
    kategori: "jasa",
    icon: "🏬",
    deskripsi: "Tempat ini menyediakan jasa pembersihan dan perawatan luar untuk kendaraan roda dua maupun roda empat dari kotoran, debu, lumpur, serta sisa oli.",
    alamat: "Jl.raja diwa tinnyu, RT02,suaran kadasa",
    jam: "10.00-23.00WITA",
    whatsapp: "6285386760748",
    mapsQuery: "-",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
    buka: true,
  },
];
