/* ============================================================
   FEIFH Link — data dasar (seed data)
   Ini adalah data BAWAAN yang dipakai saat panel admin belum
   pernah dipakai untuk mengubah apa pun di browser ini.

   Begitu Admin menambah/mengubah/menghapus data lewat admin.html,
   perubahan disimpan di localStorage browser tersebut dan akan
   dipakai menggantikan data di file ini (lihat script.js & admin.js).

   Untuk membuat perubahan permanen di semua perangkat, gunakan
   tombol "Unduh data.js" di panel admin lalu unggah file hasil
   unduhan itu untuk menimpa file data.js ini, kemudian deploy ulang.
   ============================================================ */

const CATEGORIES = [
  { id: "makanan", label: "Makanan", icon: "🍜" },
  { id: "minuman", label: "Minuman", icon: "🥤" },
  { id: "warung", label: "Warung", icon: "🏪" },
  { id: "jasa", label: "Jasa", icon: "🔧" },
];

// Data banner website — bisa diubah lewat panel admin > Pengaturan Banner
const BANNER = {
  gambar: "", // URL gambar banner (kosong = pakai SVG default)
  aktif: false, // true = tampilkan gambar, false = tampilkan SVG
};

// Data teks website — bisa diubah lewat panel admin > Pengaturan Teks
// Setiap key adalah ID elemen HTML yang akan diisi teks ini.
const SITE_TEXT = {
  heroEyebrow: "Katalog Digital UMKM · Kampung Suaran",
  heroTitle: "Jalan-jalan kampung, temukan usahanya.",
  heroDesc: "FEIFH Link mengumpulkan seluruh UMKM Kampung Suaran dalam satu tempat — lengkap dengan lokasi, jam buka, dan kontak WhatsApp, supaya Anda tinggal datang atau menghubungi langsung.",
  searchPlaceholder: "Cari nama usaha, kategori, atau lokasi…",
  stat1: "UMKM terdaftar",
  stat2: "Kategori usaha",
  stat3: "Kampung, satu tautan",
  kategoriHeading: "Mau cari yang mana hari ini?",
  katalogHeading: "Usaha di Kampung Suaran",
  aboutEyebrow: "Tentang FEIFH Link",
  aboutTitle: "Bukan marketplace. Ini jalan pintas ke tetangga Anda sendiri.",
  aboutDesc: "FEIFH Link tidak menjual apa pun dan tidak memproses pesanan. Website ini murni katalog: kami menautkan Anda ke lokasi dan nomor WhatsApp pelaku UMKM, lalu transaksi terjadi langsung antara Anda dan mereka — sama seperti membeli di warung sebelah rumah, hanya lebih mudah ditemukan.",
  aboutPoint1Title: "Terpusat",
  aboutPoint1Desc: "Seluruh UMKM kampung, dari makanan sampai jasa, ada dalam satu tautan.",
  aboutPoint2Title: "Langsung terhubung",
  aboutPoint2Desc: "Klik WhatsApp atau Google Maps, langsung terhubung ke pelaku usaha.",
  aboutPoint3Title: "Selalu diperbarui",
  aboutPoint3Desc: "Data dikelola admin kampung, sehingga informasi tetap akurat.",
  adminNote: "Punya usaha di Kampung Suaran dan belum terdaftar? Hubungi admin website untuk didaftarkan ke dalam katalog.",
  footerText: "Katalog Digital UMKM Kampung Suaran · MVP 1.0",
};

const UMKM_DATA = [
  {
    id: 1,
    nama: "Warung Bu Yuni",
    kategori: "makanan",
    icon: "🍛",
    deskripsi: "Nasi rames rumahan dengan lauk berganti tiap hari, favorit warga sekitar untuk makan siang.",
    alamat: "Jl. Suaran Raya No. 12, Kampung Suaran",
    jam: "06.00 – 15.00 WIB",
    whatsapp: "6281234567001",
    mapsQuery: "Warung Bu Yuni Kampung Suaran",
    buka: true,
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
  },
  {
    id: 2,
    nama: "Sate Kambing Pak Dulah",
    kategori: "makanan",
    icon: "🍢",
    deskripsi: "Sate kambing muda bakar arang, dibumbui resep keluarga sejak tiga generasi.",
    alamat: "Gang Melati No. 4, Kampung Suaran",
    jam: "16.00 – 21.30 WIB",
    whatsapp: "6281234567002",
    mapsQuery: "Sate Kambing Pak Dulah Kampung Suaran",
    buka: true,
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
  },
  {
    id: 3,
    nama: "Gorengan Mbak Sri",
    kategori: "makanan",
    icon: "🥟",
    deskripsi: "Gorengan hangat: tahu isi, bakwan, dan pisang goreng, digoreng dadakan setiap pesanan.",
    alamat: "Depan Balai Kampung Suaran",
    jam: "14.00 – 18.00 WIB",
    whatsapp: "6281234567003",
    mapsQuery: "Gorengan Mbak Sri Kampung Suaran",
    buka: false,
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
  },
  {
    id: 4,
    nama: "Es Kelapa Muda Cak Har",
    kategori: "minuman",
    icon: "🥥",
    deskripsi: "Es kelapa muda segar langsung dari batok, tersedia juga campuran sirup gula aren.",
    alamat: "Jl. Suaran Raya No. 25, Kampung Suaran",
    jam: "10.00 – 20.00 WIB",
    whatsapp: "6281234567004",
    mapsQuery: "Es Kelapa Muda Cak Har Kampung Suaran",
    buka: true,
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
  },
  {
    id: 5,
    nama: "Kopi Kampung Suaran",
    kategori: "minuman",
    icon: "☕",
    deskripsi: "Kedai kopi kecil dengan biji lokal, tempat nongkrong santai warga kampung.",
    alamat: "Gang Kenanga No. 2, Kampung Suaran",
    jam: "07.00 – 22.00 WIB",
    whatsapp: "6281234567005",
    mapsQuery: "Kopi Kampung Suaran",
    buka: true,
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
  },
  {
    id: 6,
    nama: "Toko Sembako Bu Marni",
    kategori: "warung",
    icon: "🧺",
    deskripsi: "Kebutuhan sehari-hari lengkap: sembako, gas LPG, hingga jajanan anak.",
    alamat: "Jl. Suaran Raya No. 3, Kampung Suaran",
    jam: "06.00 – 21.00 WIB",
    whatsapp: "6281234567006",
    mapsQuery: "Toko Sembako Bu Marni Kampung Suaran",
    buka: true,
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
  },
  {
    id: 7,
    nama: "Warung Kelontong Pak Slamet",
    kategori: "warung",
    icon: "🏪",
    deskripsi: "Warung kelontong lengkap dengan pulsa, token listrik, dan aneka kebutuhan rumah tangga.",
    alamat: "Gang Mawar No. 7, Kampung Suaran",
    jam: "05.30 – 20.30 WIB",
    whatsapp: "6281234567007",
    mapsQuery: "Warung Kelontong Pak Slamet Kampung Suaran",
    buka: true,
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
  },
  {
    id: 8,
    nama: "Bengkel Motor Pak Joko",
    kategori: "jasa",
    icon: "🔧",
    deskripsi: "Servis dan perbaikan motor harian, ganti oli, tambal ban, dan servis ringan lainnya.",
    alamat: "Jl. Suaran Raya No. 40, Kampung Suaran",
    jam: "08.00 – 17.00 WIB",
    whatsapp: "6281234567008",
    mapsQuery: "Bengkel Motor Pak Joko Kampung Suaran",
    buka: true,
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
  },
  {
    id: 9,
    nama: "Jahit Bu Ratna",
    kategori: "jasa",
    icon: "🧵",
    deskripsi: "Jasa jahit dan permak pakaian, menerima pesanan seragam dan baju custom.",
    alamat: "Gang Anggrek No. 9, Kampung Suaran",
    jam: "09.00 – 16.00 WIB",
    whatsapp: "6281234567009",
    mapsQuery: "Jahit Bu Ratna Kampung Suaran",
    buka: false,
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
  },
  {
    id: 10,
    nama: "Cuci Motor Suaran Bersih",
    kategori: "jasa",
    icon: "🧼",
    deskripsi: "Cuci motor dan mobil cepat bersih, tersedia juga cuci helm dan salon interior.",
    alamat: "Jl. Suaran Raya No. 18, Kampung Suaran",
    jam: "08.00 – 18.00 WIB",
    whatsapp: "6281234567010",
    mapsQuery: "Cuci Motor Suaran Bersih Kampung Suaran",
    buka: true,
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "",
    longitude: "",
  },
];