/* ============================================================
   FEIFH Link — data dasar (seed data)
   Ini adalah data BAWAAN yang dipakai saat panel admin belum
   pernah dipakai untuk mengubah apa pun di browser ini.

   Begitu Admin menambah/mengubah/menghapus data lewat admin.html,
   perubahan disimpan di localStorage browser tersebut dan akan
   dipakai menggantikan data di file ini (lihat script.js & admin.js).

   Untuk membuat perubahan permanen di semua perangkat, gunakan
   tombol "Unduh data.js" di panel admin lalu unggah file hasil
   unduhan itu untuk menimpa file data.js ini, kemudian deploy ulang.
   ============================================================ */

const CATEGORIES = [
  { id: "makanan", label: "Makanan", icon: "🍜" },
  { id: "minuman", label: "Minuman", icon: "🥤" },
  { id: "warung", label: "Warung", icon: "🏪" },
  { id: "jasa", label: "Jasa", icon: "🔧" },
];

// Data banner website — bisa diubah lewat panel admin > Pengaturan Banner
const BANNER = {
  gambar: "", // URL gambar banner (kosong = pakai SVG default)
  aktif: false, // true = tampilkan gambar, false = tampilkan SVG
};

// Data teks website — bisa diubah lewat panel admin > Teks Website
// Setiap key adalah ID elemen HTML yang akan diisi teks ini.
const SITE_TEXT = {
  heroEyebrow: "Katalog Digital UMKM · Kampung Suaran",
  heroTitle: "Jalan-jalan kampung, temukan usahanya.",
  heroDesc: "FEIFH Link mengumpulkan seluruh UMKM Kampung Suaran dalam satu tempat — lengkap dengan lokasi, jam buka, dan kontak WhatsApp, supaya Anda tinggal datang atau menghubungi langsung.",
  searchPlaceholder: "Cari nama usaha, kategori, atau lokasi…",
  stat1: "UMKM terdaftar",
  stat2: "Kategori usaha",
  stat3: "Kampung, satu tautan",
  kategoriHeading: "Mau cari yang mana hari ini?",
  katalogHeading: "Usaha di Kampung Suaran",
  aboutEyebrow: "Tentang FEIFH Link",
  aboutTitle: "Bukan marketplace. Ini jalan pintas ke tetangga Anda sendiri.",
  aboutDesc: "FEIFH Link tidak menjual apa pun dan tidak memproses pesanan. Website ini murni katalog: kami menautkan Anda ke lokasi dan nomor WhatsApp pelaku UMKM, lalu transaksi terjadi langsung antara Anda dan mereka — sama seperti membeli di warung sebelah rumah, hanya lebih mudah ditemukan.",
  aboutPoint1Title: "Terpusat",
  aboutPoint1Desc: "Seluruh UMKM kampung, dari makanan sampai jasa, ada dalam satu tautan.",
  aboutPoint2Title: "Langsung terhubung",
  aboutPoint2Desc: "Klik WhatsApp atau Google Maps, langsung terhubung ke pelaku usaha.",
  aboutPoint3Title: "Selalu diperbarui",
  aboutPoint3Desc: "Data dikelola admin kampung, sehingga informasi tetap akurat.",
  adminNote: "Punya usaha di Kampung Suaran dan belum terdaftar? Hubungi admin website untuk didaftarkan ke dalam katalog.",
  footerText: "Katalog Digital UMKM Kampung Suaran · MVP 1.0",
};

const UMKM_DATA = [
  {
    id: 1,
    nama: "Warung Bu Yuni",
    kategori: "makanan",
    icon: "🍛",
    deskripsi: "Warung rumahan yang menyajikan masakan sehari-hari dengan cita rasa autentik dan harga terjangkau.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Kampung Suaran",
    jam: "06.00 - 21.00 WITA",
    whatsapp: "6281234567890",
    mapsQuery: "Warung Bu Yuni Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.0143812",
    longitude: "117.6510919",
    buka: true,
  },
  {
    id: 2,
    nama: "Toko Sembako Berkah",
    kategori: "warung",
    icon: "🏪",
    deskripsi: "Toko sembako lengkap dengan berbagai kebutuhan sehari-hari, dari beras, minyak, gula, hingga kebutuhan rumah tangga lainnya.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Kampung Suaran",
    jam: "05.00 - 22.00 WITA",
    whatsapp: "6281234567891",
    mapsQuery: "Toko Sembako Berkah Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014400",
    longitude: "117.651200",
    buka: true,
  },
  {
    id: 3,
    nama: "Warung Pinarak",
    kategori: "makanan",
    icon: "🥟",
    deskripsi: "Menyajikan aneka masakan khas rumahan dengan rasa otentik dan harga yang pas di kantong.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Kampung Suaran",
    jam: "09.00 - 21.30 WITA",
    whatsapp: "6282150119167",
    mapsQuery: "Warung Pinarak Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014327",
    longitude: "117.650903",
    buka: true,
  },
  {
    id: 4,
    nama: "Masha Cell",
    kategori: "jasa",
    icon: "📱",
    deskripsi: "Melayani isi pulsa & paket data, transfer/tarik tunai, top up, pembayaran tagihan (listrik, air, wifi), hingga jasa fotocopy, print, dan desain.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Kampung Suaran",
    jam: "08.00 - 22.00 WITA",
    whatsapp: "6281258245764",
    mapsQuery: "Masha Cell Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014500",
    longitude: "117.651000",
    buka: true,
  },
  {
    id: 5,
    nama: "Penjahit Suaran Sejahtera",
    kategori: "jasa",
    icon: "🧵",
    deskripsi: "Menerima jahit baru dan permak (potong celana, ganti resleting, kecilkan baju). Hasil rapi, pengerjaan cepat, dan harga bersahabat.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Kampung Suaran",
    jam: "07.00 - 22.00 WITA",
    whatsapp: "6285248527118",
    mapsQuery: "Penjahit Suaran Sejahtera",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014548",
    longitude: "117.649873",
    buka: true,
  },
  {
    id: 6,
    nama: "Warung Mama Riyan",
    kategori: "makanan",
    icon: "🍚",
    deskripsi: "Solusi santap siang dan malam Anda. Menyajikan beragam menu favorit harian yang dimasak segar setiap hari.",
    alamat: "Gang Masuk PT Tanjung Redeb Hutani, Kampung Suaran",
    jam: "07.00 - 00.00 WITA",
    whatsapp: "6285369393553",
    mapsQuery: "Warung Mama Riyan Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014600",
    longitude: "117.650800",
    buka: true,
  },
  {
    id: 7,
    nama: "Warung Mama AL",
    kategori: "makanan",
    icon: "🍲",
    deskripsi: "Solusi santap siang dan malam Anda. Menyajikan beragam menu favorit harian yang dimasak segar setiap hari dengan pelayanan cepat.",
    alamat: "Jl. Raja Diwa Tinnyu, RT03, Kampung Suaran",
    jam: "09.00 - 00.00 WITA",
    whatsapp: "6282148690965",
    mapsQuery: "Warung Mama AL Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014700",
    longitude: "117.650900",
    buka: true,
  },
  {
    id: 8,
    nama: "Ridhoqua",
    kategori: "minuman",
    icon: "🥤",
    deskripsi: "Penyedia kebutuhan harian: pengisian ulang air galon bersih, penjualan bensin eceran, serta tabung gas LPG.",
    alamat: "Jl. Raja Diwa Tinnyu, RT03, Kampung Suaran",
    jam: "07.00 - 22.00 WITA",
    whatsapp: "6285171614376",
    mapsQuery: "Ridhoqua Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014750",
    longitude: "117.651050",
    buka: true,
  },
  {
    id: 9,
    nama: "Es Teh Untuk Negeri",
    kategori: "minuman",
    icon: "🧋",
    deskripsi: "Segarkan harimu di Es Teh Negeri! Menghadirkan kenikmatan es teh racikan asli dengan berbagai topping dan varian rasa.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Kampung Suaran (Depan Gedung Serba Guna)",
    jam: "09.00 - 22.00 WITA",
    whatsapp: "6281347280752",
    mapsQuery: "Es Teh Untuk Negeri Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014350",
    longitude: "117.650950",
    buka: true,
  },
  {
    id: 10,
    nama: "Warung Sayur Arema",
    kategori: "warung",
    icon: "🥬",
    deskripsi: "Menyediakan aneka sayuran segar, bumbu dapur, dan kebutuhan masak sehari-hari dengan harga terjangkau.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Kampung Suaran (Samping Es Teh Untuk Negeri)",
    jam: "06.00 - 18.00 WITA",
    whatsapp: "6281352480751",
    mapsQuery: "Warung Sayur Arema Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014380",
    longitude: "117.650920",
    buka: true,
  },
  {
    id: 11,
    nama: "Toko Ana Fashion",
    kategori: "warung",
    icon: "👗",
    deskripsi: "Toko fashion yang menyediakan koleksi pakaian nyaman dipakai dan cocok untuk berbagai gaya, juga aksesoris dan skincare.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Kampung Suaran",
    jam: "08.00 - 22.00 WITA",
    whatsapp: "6282290737476",
    mapsQuery: "Toko Ana Fashion Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014420",
    longitude: "117.651100",
    buka: true,
  },
  {
    id: 12,
    nama: "Warung Bakso & Mie Ayam Mak QYLA",
    kategori: "makanan",
    icon: "🍜",
    deskripsi: "Warung ini menyediakan aneka menu lezat dengan cita rasa khas dan harga yang terjangkau.",
    alamat: "Jl. Raja Diwa Tinnyu, RT04, Kampung Suaran (Dekat Pukesmas)",
    jam: "11.00 - 23.00 WITA",
    whatsapp: "6285693660450",
    mapsQuery: "Warung Bakso Mak QYLA Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014800",
    longitude: "117.651300",
    buka: true,
  },
  {
    id: 13,
    nama: "Warung Biru Arema",
    kategori: "makanan",
    icon: "🍛",
    deskripsi: "Warung ini menyediakan aneka hidangan rumahan dengan pelayanan ramah dan harga yang terjangkau.",
    alamat: "Jl. Raja Diwa Tinnyu, RT04, Kampung Suaran",
    jam: "10.00 - 22.00 WITA",
    whatsapp: "6287776659000",
    mapsQuery: "Warung Biru Arema Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014850",
    longitude: "117.651350",
    buka: true,
  },
  {
    id: 14,
    nama: "Toko Sinar Bone",
    kategori: "warung",
    icon: "🏠",
    deskripsi: "Toko ini menyediakan berbagai kebutuhan pokok dan keperluan rumah tangga sehari-hari.",
    alamat: "Jl. Raja Diwa Tinnyu, RT04, Suaran Kadasa",
    jam: "06.00 - 23.00 WITA",
    whatsapp: "6285880173693",
    mapsQuery: "Toko Sinar Bone Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014900",
    longitude: "117.651400",
    buka: true,
  },
  {
    id: 15,
    nama: "Batuah Raya",
    kategori: "warung",
    icon: "🔨",
    deskripsi: "Toko ini menyediakan berbagai bahan, peralatan, dan perlengkapan dasar untuk kebutuhan konstruksi, renovasi, serta perbaikan rumah.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Suaran Kadasa",
    jam: "08.00 - 19.00 WITA",
    whatsapp: "6285346545352",
    mapsQuery: "Batuah Raya Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.014950",
    longitude: "117.651450",
    buka: true,
  },
  {
    id: 16,
    nama: "Ngopi Nah!",
    kategori: "minuman",
    icon: "☕",
    deskripsi: "Cafe ini menyajikan berbagai olahan minuman kopi dan hidangan pendamping yang nyaman untuk bersantai.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Suaran Kadasa",
    jam: "10.00 - 23.00 WITA",
    whatsapp: "6285155155374",
    mapsQuery: "Ngopi Nah Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.015000",
    longitude: "117.651500",
    buka: true,
  },
  {
    id: 17,
    nama: "Lapak Al Fatir",
    kategori: "warung",
    icon: "🐟",
    deskripsi: "Warung ini menyediakan berbagai jenis ikan dan ayam segar dengan harga bersaing.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Suaran Kadasa",
    jam: "07.00 - 21.00 WITA",
    whatsapp: "6285175217992",
    mapsQuery: "Lapak Al Fatir Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.015050",
    longitude: "117.651550",
    buka: true,
  },
  {
    id: 18,
    nama: "AZ AZAHRA SHOP",
    kategori: "warung",
    icon: "🛍️",
    deskripsi: "Toko ini menyediakan berbagai koleksi fashion dan aksesoris pendukung dengan harga terjangkau.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Suaran Simpang",
    jam: "06.00 - 21.00 WITA",
    whatsapp: "6282290737477",
    mapsQuery: "AZ AZAHRA SHOP Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.015100",
    longitude: "117.651600",
    buka: true,
  },
  {
    id: 19,
    nama: "Adi Karya Jaya Motor",
    kategori: "jasa",
    icon: "🔧",
    deskripsi: "Bengkel ini menyediakan berbagai jasa untuk kendaraan bermotor, mesin atau peralatan teknis lainnya.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Suaran Simpang",
    jam: "07.00 - 17.00 WITA",
    whatsapp: "6282148783556",
    mapsQuery: "Adi Karya Jaya Motor Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.015150",
    longitude: "117.651650",
    buka: true,
  },
  {
    id: 20,
    nama: "Pencucian Motor Sanggam",
    kategori: "jasa",
    icon: "🚿",
    deskripsi: "Tempat ini menyediakan jasa pembersihan dan perawatan luar untuk kendaraan roda dua maupun roda empat dari kotoran, debu, lumpur, serta sisa oli.",
    alamat: "Jl. Raja Diwa Tinnyu, RT02, Suaran Kadasa",
    jam: "10.00 - 23.00 WITA",
    whatsapp: "6285386760748",
    mapsQuery: "Pencucian Motor Sanggam Kampung Suaran",
    fotoUsaha: "",
    fotoProduk: "",
    latitude: "2.015200",
    longitude: "117.651700",
    buka: true,
  },
];